### DISCUSSION TITLE
How to use animation fade-in / fade-out?

### DISCUSSION THREAD

**Discussion by szymonleyk** [igordanchenko/yet-another-react-lightbox#149] [Q&A] [answered]
I try to set fade-in/out animation, could you help me?

`animation={{
          fade: 3000,
          swipe: 500,
          easing: {
            fade: "?",
            swipe: "?",
            navigation: "?",
          },
        }}
`

**Comment by igordanchenko** [comment]
Can you clarify your question?

**Reply by szymonleyk** [reply]
Sure, I want to get the effect of fading successive slides.

Example: https://codepen.io/takayuki-kojima/pen/bONKxg

**Reply by igordanchenko** [reply, marked as answer]
Thank you for providing this example. Lightbox animation settings that you mentioned above control the fade-in / fade-out effect of the entire lightbox when the lightbox opens / closes, not when individual slides change. 

This library was designed for touch-swipe / click-and-drag navigation, and the effect that you want to implement doesn't fit well in the current implementation. You can probably achieve the desired effect with some custom styling, but I can't guarantee the end result. 

Please feel free to use the following sandbox as an inspiration.

https://codesandbox.io/p/sandbox/yet-another-react-lightbox-149-6ccmmz?file=%2Fsrc%2FApp.css

**Update (3/2025):** the above sandbox is no longer available due to CodeSandbox's free tier billing changes, but here is the CSS that was used in that example:

```css
.yarl__carousel,
.yarl__slide {
  position: absolute;
  inset: 0;
  width: unset;
  height: unset;
  transform: unset;
}

.yarl__slide {
  opacity: 0;
  transition: opacity 0.6s ease-in-out;
}

.yarl__slide_current {
  opacity: 1;
}
```
