### DISCUSSION TITLE
Position toolbar below the inline carousel

### DISCUSSION THREAD

**Discussion by stevenfeltner** [igordanchenko/yet-another-react-lightbox#165] [Q&A] [answered]
Hi, 

Can someone help me with getting the toolbar to be below the carousel? I've tried styles and also a module scoped CSS. Basically looking to get the toolbar to not sit on top of the image/s. I've tried changing the container to use relative and flex-direction: column without much success. Thank you in advance!

**Comment by igordanchenko** [comment, marked as answer]
Hi!

Currently the toolbar is rendered relative to the carousel. If you want to position it at the bottom of the carousel you can tweak its position with the following css.

```tsx
export default function App() {
    return (
        <Lightbox
            slides={slides}
            plugins={[Inline, Download, Fullscreen, Slideshow]}
            inline={{ style: { width: 400, height: 300, margin: "0 auto" } }}
            carousel={{ padding: 0, spacing: 0, imageFit: "cover" }}
        />
    );
}
```

```css
.yarl__toolbar {
    top: unset;
    bottom: 0;
}
```

<img width="415" alt="Screenshot 2023-07-28 at 8 29 22 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/efa7c963-7dfe-4d70-984d-640fedcc9708">

However, positioning the toolbar below the carousel is not supported out of the box. You'd need to add an extra `<div>` wrapper to achieve the desired layout.

```tsx
import { Lightbox, MODULE_CONTROLLER, createModule, ComponentProps, PluginProps } from "yet-another-react-lightbox";

function CarouselWrapper({ children }: ComponentProps) {
    return <div className="yarl__carousel_wrapper">{children}</div>;
}

function CarouselWrapperPlugin({ addParent }: PluginProps) {
    addParent(MODULE_CONTROLLER, createModule("carousel-wrapper", CarouselWrapper));
}

export default function App() {
    return (
        <Lightbox
            slides={slides}
            plugins={[Inline, Download, Fullscreen, Slideshow, CarouselWrapperPlugin]}
            inline={{ style: { width: 400, height: 300, margin: "0 auto" } }}
            carousel={{ padding: 0, spacing: 0, imageFit: "cover" }}
        />
    );
}
```

```css
.yarl__root {
    background-color: black;
    overflow: hidden;
}

.yarl__container {
    overflow: visible;
}

.yarl__carousel_wrapper {
    inset: 0;
    position: absolute;
    margin-bottom: 64px;
}

.yarl__toolbar {
    top: unset;
    bottom: -64px;
}
```

<img width="421" alt="Screenshot 2023-07-28 at 8 27 28 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/4960ed4f-1c66-4b59-8576-cec4990192b3">

Is this the layout you have in mind? Please feel free to share a screenshot of your end result if you'd like to make a case for it to be supported by the library.
