### DISCUSSION TITLE
Image goes over Toolbar (custom buttons)

### DISCUSSION THREAD

**Discussion by ivanjeremic** [igordanchenko/yet-another-react-lightbox#226] [Q&A] [answered]
The Image should not go over the Toolbar and behind my custom buttons, can anyone help me to fix this?

![lightbox-problem](https://github.com/igordanchenko/yet-another-react-lightbox/assets/13917696/936160e1-7247-485a-aea5-9e78dd9a9a92)

**Comment by igordanchenko** [comment]
This is actually the intended behavior - see how the standard buttons hover over an image.

<img width="745" alt="Screenshot 2024-01-21 at 10 25 32 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/8b67fdde-af32-485b-95a7-ef9a2062d715">

> can anyone help me to fix this?

It would be helpful if you could describe the fix you have in mind or provide a visual mockup.

**Reply by ivanjeremic** [reply]
The image should scale down so that it is under the toolbar. The toolbar should be an area where no image can go over.

**Reply by igordanchenko** [reply, marked as answer]
It sounds like you can make the desired adjustments with the following css:

```css
.yarl__root {
  background-color: black;
}

.yarl__container {
  overflow: visible;
  margin-top: 48px;
}

.yarl__toolbar, .yarl__counter {
  top: -48px
}
```
