### DISCUSSION TITLE
Cannot customize max-height css property for image in lightbox

### DISCUSSION THREAD

**Discussion by jimdigrease** [igordanchenko/yet-another-react-lightbox#233] [Q&A] [answered]
Tried to do this (in styled-component): 

```css
.lightbox :global(.yarl__slide_image) {
  max-height: 86%;
}
```
 
that do nothing. 

The goal is to left more space above and below image to show centered titles and captures to not overlay with it. Have not found another solution. Any help, please. What am I doing wrong?

**Comment by igordanchenko** [comment, marked as answer]
You can increase the padding around each slide with the following setting:

```js
carousel={{ padding: 64 }}
```

but that increases padding on all 4 sides, not just on the vertical axis.

You can also override the inline style rendered by the library with `!important`:

```css
.yarl__slide_image {
  max-height: 86% !important;
}
```

Please let me know if the above addresses your use case.

**Reply by jimdigrease** [reply]
Yes, just for height.
Sorry for bother, forgot this option, 

```css
.lightbox :global(.yarl__slide_image) {
  max-height: 86% !important;
}
``` 

this does work
