### DISCUSSION TITLE
Gallery open animation

### DISCUSSION THREAD

**Discussion by kowalczyk-mateusz** [igordanchenko/yet-another-react-lightbox#240] [Q&A] [answered]
Hello, is it possible to change gallery open animation? right now, the animation looks like: opacity: 0 -> opacity: 1. And I would like to also add a scale animation to open, from 0.9 to 1 together with opacity animation. I tried to change container in render method, but it broke styles for images etc

**Comment by igordanchenko** [comment]
Hi there!

> Hello, is it possible to change gallery open animation?

Have you tried adjusting fade animation settings? You can adjust fade animation duration and the timing function.

https://yet-another-react-lightbox.com/documentation

> And I would like to also add a scale animation to open, from 0.9 to 1 together with opacity animation.

Is this the effect you are trying to achieve?

```css
.yarl__portal {
  transform: scale(0.9);
  transition: transform 0.25s ease;
}

.yarl__portal_open {
  transform: scale(1);
}
```
