### DISCUSSION TITLE
Touch and hold to download an image in mobile browser

### DISCUSSION THREAD

**Discussion by ruben-sandoval** [igordanchenko/yet-another-react-lightbox#269] [Q&A] [answered]
Hi,
When using Safari on iOS, touch and hold usually let me download images to "Photos".
These are all the options I get by default Open, Open in New Tab, Open in Tab Group, Download Linked File, Add to Reading List, Save to Photos, Copy, Share.
yet-another-react-lightbox does not show the popup when I touch and hold on an image in the lightbox.
Is there an option / property to show the popup?
Thanks

**Comment by igordanchenko** [comment, marked as answer]
While `yet-another-react-lightbox` does not provide a configuration option for this, you can override the existing implementation with the following CSS:

```css
.yarl__slide_image {
  -webkit-touch-callout: initial;
}
```

You may also need to disable `user-select` on the whole lightbox to prevent awkward text/image selection side-effect of a touch callout:

```css
.yarl__root {
  user-select: none;
  -webkit-user-select: none;
}
```

![screenshot](https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/4a771cb7-d504-4a6a-9f47-3491b019226a)
