### DISCUSSION TITLE
Question about hiding toolbar, title, and description for a custom slide

### DISCUSSION THREAD

**Discussion by dronem** [igordanchenko/yet-another-react-lightbox#324] [Q&A] [answered]
Hi,

Thank you for creating such a fantastic library! I'm currently using Yet Another React Lightbox and have a specific question regarding customization.

I have a custom slide, and I'd like to hide the toolbar, title, and description only when this specific slide is displayed. Is there a way to achieve this behavior? If so, could you guide me on how to implement it?

Thanks in advance for your help!

Best regards,

**Comment by igordanchenko** [comment, marked as answer]
Please see if the following approach works for you.

```tsx
import "./yarl.css";

// ..

const [index, setIndex] = React.useState<number>();
const [hideControls, setHideControls] = React.useState(false);

// ...

<Lightbox
  index={index}
  open={index !== undefined}
  close={() => setIndex(undefined)}
  on={{
    view: ({ index: currentIndex }) => {
      setIndex(currentIndex);
      setHideControls(slides[currentIndex].type === "custom-slide");
    },
  }}
  className={hideControls ? "yarl__hide-controls" : undefined}
  // ...
/>
```

```css
/* yarl.css */

.yarl__hide-controls .yarl__toolbar,
.yarl__hide-controls .yarl__slide_captions_container {
  visibility: hidden;
}
```
