### DISCUSSION TITLE
Not using the lightbox fullscreen - can't close when clicking outside

### DISCUSSION THREAD

**Discussion by drina-musaj** [igordanchenko/yet-another-react-lightbox#371] [Q&A] [answered]
Hello!
I've been trying to use YARL as a lightbox but not on fullscreen. I want the background to be dark transparent and show the page in the back, but also have a white container around the media.
When i try the  controller={{ closeOnBackdropClick: true }} it doesn't work because of my customizations.
Is there a better way to do this? I think it doesn't recognize the backdrop as a yarl__root. But only as a container.
Help would be appreciated!

**Comment by igordanchenko** [comment]
I won't be able to answer your question as you forgot to share a code snippet demonstrating your customizations, but here is one way to implement the requirements you described.

```css
/* styles.css */

.yarl__root {
  --yarl__color_backdrop: rgba(0, 0, 0, 0.3);
}

.yarl__slide_image {
  outline: 2px solid white;
  outline-offset: 4px;
}
```

I hope this helps.
