### ISSUE TITLE
Click/Tap to hide UI

### ISSUE THREAD

**Issue by gergoradeczki** [igordanchenko/yet-another-react-lightbox#78]
### Is your feature request related to a problem? Please describe.

The ration between the UI and the image feels bad on mobile devices from a UX point of view.

### Describe the solution you'd like

Clicking/Tapping once on the image should hide the UI, but clicking/tapping again shows it again.

**Comment by igordanchenko** [comment]
I'm not sure what you mean by ration in this context, but you can implement the described behavior in the user land.

```jsx
import "./yarl.css";

// ...

const [hideControls, setHideControls] = React.useState(false);

// ...

<Lightbox
  on={{ click: () => setHideControls((state) => !state) }}
  className={hideControls ? "yarl__hide-controls" : undefined}
  // ...
/>
```

```css
/* yarl.css */

.yarl__hide-controls .yarl__navigation_prev,
.yarl__hide-controls .yarl__navigation_next,
.yarl__hide-controls .yarl__toolbar {
    visibility: hidden;
}
```
